monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/dev.log"
            level: debug
            channels: ["!event"]
        security:
            type: rotating_file
            path: "%kernel.logs_dir%/security.log"
            level: debug
            channels: ["security"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]