vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        curso_archivos:
            uri_prefix: /uploads/cursos
            upload_destination: '%kernel.project_dir%/public/uploads/cursos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
